export const userTypes = [
  {
    type: 'player',
    title: 'Jugador',
    description: 'Únete a torneos, encuentra compañeros y sigue tu clasificación',
    color: 'bg-blue-500',
    features: [
      'Registro en torneos',
      'Buscador de jugadores',
      'Seguimiento de clasificación',
      'Programación de partidos',
    ],
  },
  {
    type: 'coach',
    title: 'Entrenador',
    description: 'Ofrece sesiones de entrenamiento y gestiona tu negocio de coaching',
    color: 'bg-green-500',
    features: [
      'Sesiones de entrenamiento',
      'Gestión de estudiantes',
      'Evaluaciones de habilidades',
      'Calendario de entrenamiento',
    ],
  },
  {
    type: 'club',
    title: 'Club',
    description: 'Gestiona tu club de pickleball y las reservas de canchas',
    color: 'bg-purple-500',
    features: [
      'Gestión de canchas',
      'Gestión de miembros',
      'Organización de torneos',
      'Alquiler de equipamiento',
    ],
  },
  {
    type: 'partner',
    title: 'Socio',
    description: 'Alianzas comerciales y venta de equipamiento',
    color: 'bg-orange-500',
    features: [
      'Venta de equipamiento',
      'Oportunidades de patrocinio',
      'Networking empresarial',
      'Alianzas para eventos',
    ],
  },
  {
    type: 'state',
    title: 'Comité Estatal',
    description: 'Gestiona actividades de pickleball a nivel estatal y asociaciones regionales',
    color: 'bg-red-500',
    features: [
      'Torneos estatales',
      'Gestión regional',
      'Supervisión de miembros',
      'Micrositio estatal',
    ],
  },
];

export const MEXICAN_STATES = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila',
  'Colima',
  'Durango',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
] as const;
